name: Feature Request
description: Suggest a new feature or improvement (e.g., better memory control, new query option)
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Help us understand the motivation and scope.

  - type: textarea
    id: problem_or_motivation
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Why is it needed?
      placeholder: |
        e.g. "Current vector queries don't allow filtering by metadata + distance threshold at once"
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How should it work? API sketch or pseudocode welcome.
      placeholder: |
        Add `filter=` and `max_distance=` args to `Zvec.query()`:
        ```python
        results = db.query(vector, filter="category == 'A'", max_distance=0.5)
        ```
      render: python
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there workarounds? Why not use them?
    validations:
      required: false

  - type: dropdown
    id: impact_area
    attributes:
      label: Affected Area
      multiple: true
      options:
        - label: C++ Core (storage, indexing)
        - label: Python API / Bindings
        - label: Build System (CMake, Homebrew pkg)
        - label: Testing / CI / Coverage
        - label: Documentation
    validations:
      required: false